### ISSUE TITLE
questions about results

### ISSUE THREAD

**Issue by jessapinkman** [Tsinghua-MARS-Lab/StateTransformer#149]
hey!
    I noticed that in open-loop simulations, STR achieved better performance because evaluation metrics like FDE and ADE are commonly used for prediction tasks. However, in closed-loop simulations, STR performed poorly. I do not deny that STR shows good performance on prediction tasks, but on the nuplan dataset, a good prediction model cannot be converted into closed-loop capabilities. I'm confused about the huge gap between CLS and OLS. Can you provide some more insights into the performance of STR on the nuplan dataset? THANKS!

**Comment by larksq** [comment]
Hi there, 

I would like to share this paper "[Parting with Misconceptions about Learning-based Vehicle Motion Planning](https://arxiv.org/abs/2306.07962)"
by the team of Prof. [Andreas Geiger](https://arxiv.org/search/cs?searchtype=author&query=Geiger,+A) with you for your question. They have discussed this gap in depth and provided a simple yet effective way to solve it by providing IDM planning results as references during training.  

Don't hesitate to contact me by email if you have more questions or ideas in mind to discuss.

**Comment by jessapinkman** [comment]
Thanks for the replay. Well, that is the shortness of the nuplan dataset.
 Another question: Have you ever tried to use simple post-solve technology for STR? Is this obvious help for STR? Although I know you may want to build a pure learning model.

**Comment by larksq** [comment]
We did try some very limited tries and post-solvers did help especially when the models were weak.
You can implement and try some during the generation process like this [off-road checking codes](https://github.com/Tsinghua-MARS-Lab/StateTransformer/blob/b140e1938f47f45776a49a80a4ca9630d1ee7bdf/transformer4planning/models/backbone/str_base.py#L358) (which is under work-in-progress condition). PRs are welcome!

**Comment by jessapinkman** [comment]
Alright, thanks a lot for your kind reply and contribution.
I will close it.
