### ISSUE TITLE
lightning and torch version incompatible

### ISSUE THREAD

**Issue by Chufan1990** [Tsinghua-MARS-Lab/StateTransformer#152]
According to https://lightning.ai/docs/pytorch/stable/versioning.html#compatibility-matrix
lightning==1.3.8 only compatible with torch >=1.4, <=1.8. In the install instruction, however, torch is 1.9.0. It caused forced update on torch from 1.9.0 to 2.2.0 on my pc and lead to incompatibility between torch and cuda.

**Comment by larksq** [comment]
Probably try to use a newer version of the lightning lib? 

For your information, I am using the following package versions:
pytorch_lightning: 2.2.2
torch: 2.4.0.dev20240320+cu121
CUDA: 12.2
Another older version environment also works:
pytorch_lightning: 1.6.3
torch: 2.0.0+cu117
CUDA: 12.2

Please let me know if you have to use the 1.3.8 version of lightning or run into any new problems.

**Comment by Chufan1990** [comment]
> Probably try to use a newer version of the lightning lib?
> 
> For your information, I am using the following package versions: pytorch_lightning: 2.2.2 torch: 2.4.0.dev20240320+cu121 CUDA: 12.2 Another older version environment also works: pytorch_lightning: 1.6.3 torch: 2.0.0+cu117 CUDA: 12.2
> 
> Please let me know if you have to use the 1.3.8 version of lightning or run into any new problems.

it worked. Thanks
