### ISSUE TITLE
Cannot reproduce the evaluation numbers for motion planning

### ISSUE THREAD

**Issue by youngsjin92** [Tsinghua-MARS-Lab/StateTransformer#159]
Comparing with the planning evaluation numbers of table 1 in your paper, trained mini or small models from my side give lower evaluation numbers as shown in the below table.

I use the data which you shared in the following [link](http://180.167.251.46:880/NuPlanSTR/nuplan-v1.1_STR.zip).
I execute my training work through the first command example in [To train and evaluate during training:](https://github.com/Tsinghua-MARS-Lab/StateTransformer?tab=readme-ov-file#to-train-and-evaluate-during-training) and I checked that my training arguments are identical to your training arguments.

Are any additional steps required to re-produce your numbers? (Such as use pre-trained weights, data augmentation/processing or others.)

<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>

  | 8sADE | 3sFDE | 5sFDE | 8sFDE | MR
-- | -- | -- | -- | -- | --
Paper   - Mini | 2.07 | 1.20 | 2.43 | 5.14 | 0.067
Re-prod - Mini | 3.12 | 1.93 | 3.86 | 6.99 | 0.162
Paper   - Small | 1.91 | 1.05 | 2.22 | 4.83 | 0.049
Re-prod - Small | 2.08 | 1.19 | 2.47 | 5.05 | 0.070

</body>

</html>

Thanks.

**Comment by larksq** [comment]
Hi, glad to help reproduce the training results. 

The most likely gap is** the size of the training dataset**. Our original training used a dataset with about 700M data samples. The dataset from the link has about 70M training samples with a 1/10 sampling frequency. The best way to scale up is to add this '--augment_index 5' to your training arguments. This arg triggers a random index offset from -5 to 5 making it the same as training with a 10 times more dense training sampling. 

You can try this with the mini model for quick verification. Let me know if it does not work. We will also schedule a retrain with the latest version of our code on our server to double-check.

**Comment by youngsjin92** [comment]
Thanks for sharing your results. The number you shared in the previous command comes from the mini planning model with '--augment_index 5', right?

In addition, I have few questions.
1. Why are the number of data samples reduced to 700M to 70M?
2. In your paper, you mentioned that the number of data samples is 15M (15,523,077 samples), and 15M samples are used in my training process. Why are the number of samples different from what you mentioned (700/70M -> 15M)?
3. Are the evaluation numbers in table 1 of your original paper from the models with the diffusion decoder or MLP decoder?

**Comment by larksq** [comment]
Sorry for the confusion. To your previous questions:

1. The number of the training set can vary due to different filtering. Let me clarify a few numbers:
- The number of the uploaded dataset should be 7,191,710 (7M, not 70M, sorry for the wrong number from the previous reply)
- By using augment_index, the result should be the same as an x10 sampling frequency, meaning 70M, due to a random frame sample offset.
- For the paper, we used an older version of the training dataset of 15M.
2. The 15M -> 7M difference might be due to a still-filtering we use during dataset generation. This means about half of the samples are completely still for the whole scenario. Check the flag 'filter_still' in generation.py for more.
3. The evaluation numbers in Table 1 are from the diffusion decoder.

**Comment by youngsjin92** [comment]
Thanks for your reply.

What I am confused is that the model using a checkpoint you shared in [this link](http://180.167.251.46:880/NuPlanSTR/checkpoints/Small_CKS_PI2.zip) is identical to your number STR(CKS)-16m in Table 1, and this model is with a MLP decoder.

As you said that the models in Table 1 use a diffusion decoder, are the results in Table 1 from smaller training samples?
(I am curious why the model with a MLP decoder using your checkpoint is as good as the model with a diffusion decoder)
