### ISSUE TITLE
Question about Training.

### ISSUE THREAD

**Issue by Yyb-XJTU** [Tsinghua-MARS-Lab/StateTransformer#190]
When I try to train, it always gets stuck at this point, and the log shows the following figure：
<img width="717" alt="Snipaste_2024-11-26_16-25-01" src="https://github.com/user-attachments/assets/a8c30d22-cbda-4f4e-85b9-6fe3df8a08e3">

**Comment by Yyb-XJTU** [comment]
I have found this problem: I use "CUDA_VISIBLE_DEVICES=1, 2, 3 python runner.py" to perform multi-card training, and it seems that it is not supported. When I use "CUDA_VISIBLE_DEVICES=1 python runner.py", it can run normally.

**Comment by hz3014** [comment]
> I have found this problem: I use "CUDA_VISIBLE_DEVICES=1, 2, 3 python runner.py" to perform multi-card training, and it seems that it is not supported. When I use "CUDA_VISIBLE_DEVICES=1 python runner.py", it can run normally.

Hi, I am also trying to train the code but i have encountered errors in nuplan_rasterize.py as described in #197 
I was wondering did you modify the code or the original code just trains smoothly?
I was also thinking if it is the argument setting which brings the error, would you please share you argument?
