### ISSUE TITLE
Question about Closed Simulation

### ISSUE THREAD

**Issue by AQingRoad** [Tsinghua-MARS-Lab/StateTransformer#194]
I am using the datasets and checkpoints from Huggingface to run the following command:
```
python run_simulation_closed.py \
--test_type closed_loop_nonreactive_agents \
--data_path /home/linux/Desktop/nuplan-v1.1_STR_2/val/all_cities/ \
--map_path /home/linux/Desktop/nuplan-v1.1_STR_2/map/ \
--model_path /home/linux/Desktop/str_open/cpks100m/checkpoint-66000/ \
--split_filter_yaml /home/linux/Desktop/StateTransformer/nuplan_simulation/test14_hard.yaml \
--max_scenario_num 10000 \
--batch_size 1 \
--device cuda \
--exp_folder TestHard14_MixtralM_CKS_SepLoss_AugCur50Pct_PastProj_S6_bf16_Jun28_ckpt150k
```
There have been no changes to the `test14_hard.yaml`. The following logs are generated:

Extracting scenarios... False
Filtering with yaml file...
No log files found! This may mean that you need to set your environment, or that all of your log files got filtered out on this worker.
Got scenarios  0
Running simulations...
total scenarios: 0
locally deal with split: [0, 0]
local scenarios: 0

Thank you very much for your answer!

**Comment by JohnZhan2023** [comment]
Our provided sh command is as follows:
```sh
python run_simulation_closed.py \
    --data_path ${DATA_PATH} \
    --map_path ${NUPLAN_MAP_ROOT} \
    --model_path ${MODEL_PATH} \
    --split_filter_yaml ${SPLIT_FILTER_YAML} \
    --initstable_time 8 \
    --conservative_factor 0.8 \
    --comfort_weight 10.0 \
    --batch_size 7 \
    --processes-repetition 5 \
	--test_type 'closed_loop_reactive_agents' \
    --pdm_lateral_offsets none;
```

**Comment by JohnZhan2023** [comment]
About your error, we rerun the command given and get the result below:
![img_v3_02h6_57e35c09-9dc9-45d2-8048-66d8cacd021g](https://github.com/user-attachments/assets/d8b775a5-a472-412e-bc13-f840e0a19dd0)

**Comment by AQingRoad** [comment]
@JohnZhan2023 Thank you for your reply. I got it .

**Comment by txj531** [comment]
> @JohnZhan2023谢谢你的回复。我明白了。

您好！我也是从Hugging Face Dataset上下载的数据集，遇到了和您同样的问题，如果您解决了能分享一下解决后的data_path,map_path吗？非常感谢！

**Comment by AQingRoad** [comment]
@txj531 你直接到官网里面下载那个mini数据集或者test数据集就能使用.90G左右。data_path 对应有db文件夹的目录
